name: Build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          sudo apt-get update -y && sudo apt-get install cmake liblapack-dev libmetis-dev
          git clone --depth 1 -b latest https://github.com/ERGO-Code/HiGHS.git && cd HiGHS && cmake -DHIPO=ON -DBLA_VENDOR=Generic -DBUILD_CXX_EXE=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DCMAKE_UNITY_BUILD=ON -B build . && make -j4 -C build && sudo make install -C build
      - name: Build
        run : |
          cmake .
          make

